server:
  port: 8763

spring:
  profiles: eureka3

eureka:
  instance:
    hostname: eureka3
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8764/eureka
feign:
  hystrix:
    enabled: true