server:
  port: 8762

spring:
  profiles: eureka2

eureka:
  instance:
    hostname: eureka2
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8763/eureka,http://localhost:8764/eureka
feign:
  hystrix:
    enabled: true