server:
  port: 8764

spring:
  profiles: eureka4

eureka:
  instance:
    hostname: eureka4
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
feign:
  hystrix:
    enabled: true