server:
  port: 8040
spring:
  application:
    name: lookbi-cloud-service-config-server
  cloud: 
    config: 
      server:
        git:
          uri: https://github.com/z201/learning-spring-cloud-micro-service        # 配置git仓库的地址
          search-paths: config                                   # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                                   # git仓库的账号
          password:                                                   # git仓库的密码
    bus:
      ack:
        enabled: true  ## 开启消息跟踪
  rabbitmq: 
    addresses: 192.168.1.15
    host: 15672
    username: guest
    password: guest
eureka: 
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8763/eureka/,http://${eureka.instance.hostname}:8764/eureka/

management:
  security:
    enabled: false  ## 刷新时，关闭安全验证
